routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', HomeController::class)->name('home');
Route::get('about', AboutController::class)->name('about');
Route::get('delivery', DeliveryController::class)->name('delivery');
Route::get('terms', TermsController::class)->name('terms');
Route::get('search', SearchController::class)->name('search');

Route::resource('products', ProductController::class);
Route::resource('categories', CategoryController::class);
Route::resource('collections', CollectionController::class);

Route::get('quick-product/{product}', 'ProductController@quickShow');

Route::prefix('contact')
    ->group(function ($router) {
        $router->get('/', 'ContactController@index')->name('contact.index');
        $router->post('/', 'ContactController@store')->name('contact.store');
    });

Route::get('cart/content', CartContentController::class)->middleware('check.cart')->name('cart.content');
Route::put('cart/content', 'CartController@updateBulk')->name('cart.content.update');
Route::get('cart/count', 'CartController@count')->name('cart.count');
Route::resource('cart', CartController::class)->only('index', 'store', 'update', 'destroy');

Route::resource('checkout', CheckoutController::class);

Route::namespace('Admin')
    ->prefix('admin')
    ->as('admin.')
    ->middleware(['auth'])
    ->group(function ($router) {
        $router->get('/', HomeController::class);

        $router->resource('collections', CollectionController::class);
        $router->resource('categories', CategoryController::class);
        $router->resource('products', ProductController::class);
        $router->resource('colors', ColorController::class);
        $router->resource('sizes', SizeController::class);
        $router->resource('cloths', ClothController::class);
        $router->resource('products.colors', ProductColorController::class)->only('index', 'store');
        $router->resource('products.sizes', ProductSizeController::class)->only('index', 'store');
        $router->resource('products.cloths', ProductClothController::class)->only('index', 'store');
        $router->resource('products.pictures', ProductPictureController::class)->only('index', 'store', 'destroy');

        $router->resource('orders', OrderController::class);
        $router->resource('orders.details', OrderDetailController::class);

        $router->resource('first-page', FirstPagePictureController::class)->only('index', 'store', 'destroy');

        $router->resource('about', AboutController::class)->only('index', 'store');
        $router->resource('delivery', DeliveryController::class)->only('index', 'store');
        $router->resource('terms', TermsController::class)->only('index', 'store');
    });

app/Collection.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Nicolaslopezj\Searchable\SearchableTrait;

class Collection extends Model
{
    use SearchableTrait;

    protected $fillable = [
        'name'
    ];

    protected $searchable = [
        'columns' => [
            'name' => 10
        ]
    ];
}

app/Http/Controllers/Admin/CollectionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Collection;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CollectionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $collections = Collection::search($request->search)
            ->orderBy($request->input('sort', 'id'), $request->input('order', 'asc'))
            ->paginate(10);

        return view('admin.collections.index', compact('collections'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.collections.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $this->validate($request, [
            'name' => 'required|max:255|unique:collections,name'
        ]);

        Collection::create($validated);

        return redirect()->route('admin.collections.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Collection  $collection
     * @return \Illuminate\Http\Response
     */
    public function show(Collection $collection)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Collection  $collection
     * @return \Illuminate\Http\Response
     */
    public function edit(Collection $collection)
    {
        return view('admin.collections.edit', compact('collection'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Collection  $collection
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Collection $collection)
    {
        $validated = $this->validate($request, [
            'name' => 'required|max:255|unique:collections,name'
        ]);

        $collection->update($validated);

        return redirect()->route('admin.collections.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Collection  $collection
     * @return \Illuminate\Http\Response
     */
    public function destroy(Collection $collection)
    {
        //
    }
}

app/Http/Controllers/CollectionController.php
<?php

namespace App\Http\Controllers;

use App\Size;
use App\Color;
use App\Product;
use App\Collection;
use Illuminate\Http\Request;

class CollectionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return redirect()->route('collections.show', [1]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Collection  $collection
     * @return \Illuminate\Http\Response
     */
    public function show($collectionId)
    {
        $products = Product::with('pictures', 'sizes', 'colors')
            ->byCollection($collectionId)
            ->paginate(10);

        $colors = Color::byCategory($collectionId)->get();
        $sizes = Size::byCategory($collectionId)->get();

        return view('products.index', compact('products', 'colors', 'sizes'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Collection  $collection
     * @return \Illuminate\Http\Response
     */
    public function edit(Collection $collection)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Collection  $collection
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Collection $collection)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Collection  $collection
     * @return \Illuminate\Http\Response
     */
    public function destroy(Collection $collection)
    {
        //
    }
}

resources/views/admin/collections/create.blade.php
@extends('adminlte::page')

@section('content')
    @box
        @slot('buttons')
            <a href="{{ route('admin.collections.index') }}" class="btn btn-default">
                <i class="fa fa-backward"></i>
                Inapoi
            </a>
        @endslot

        {!! Form::open()->route('admin.collections.store') !!}
            {!! Form::text('name', 'Nume') !!}
            {!! Form::submit('Salveaza')->success() !!}
        {!! Form::close() !!}
    @endbox
@endsection

resources/views/admin/collections/edit.blade.php
@extends('adminlte::page')

@section('content')
    @box
        @slot('buttons')
            Editeaza colectie #{{ $collection->id }}
        @endslot

        {!! Form::open()->put()->route('admin.collections.update', [$collection->id])->fill($collection) !!}
            {!! Form::text('name', 'Nume') !!}
            {!! Form::submit('Modifica') !!}
            {!! Form::anchor('Inapoi')->route('admin.collections.index') !!}

        {!! Form::close() !!}
    @endbox
@endsection

resources/views/admin/collections/index.blade.php
@extends('adminlte::page')

@section('content')
    @box
        @slot('buttons')
            <div class="col-md-6">
                @add(['route' => 'admin.collections.create', 'name' => 'colectie'])
                @endadd
            </div>

            <div class="col-md-6">
                @search(['route' => 'admin.collections.index'])
                @endsearch
            </div>
        @endslot

        @if ($collections->count())
            <table class="table table-bordered table-hover">
                @theader(['columns' => [
                    'id' => 'Id',
                    'name' => 'Nume',
                    'created_at' => 'Creat la',
                    'updated_at' => 'Modificat la',
                    'none' => 'Actiuni'
                ]])
                @endtheader

                <tbody>
                    @foreach ($collections as $collection)
                        <tr>
                            <td>{{ $collection->id }}</td>
                            <td>{{ $collection->name }}</td>
                            <td>{{ $collection->created_at->format('d.m.Y H:i:s') }}</td>
                            <td>{{ $collection->updated_at->format('d.m.Y H:i:s') }}</td>
                            <td>
                                <a href="{{ route('admin.collections.edit', $collection->id) }}" class="btn btn-xs">
                                    <i class="fa fa-edit"></i>
                                </a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

            {{ $collections->links() }}
        @else
            Nu exista inregistrari
        @endif
    @endbox
@endsection

@section('js')
@endsection