routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', HomeController::class)->name('home');
Route::get('about', AboutController::class)->name('about');
Route::get('delivery', DeliveryController::class)->name('delivery');
Route::get('terms', TermsController::class)->name('terms');
Route::get('search', SearchController::class)->name('search');

Route::resource('products', ProductController::class);
Route::resource('categories', CategoryController::class);
Route::resource('collections', CollectionController::class);

Route::get('quick-product/{product}', 'ProductController@quickShow');

Route::prefix('contact')
    ->group(function ($router) {
        $router->get('/', 'ContactController@index')->name('contact.index');
        $router->post('/', 'ContactController@store')->name('contact.store');
    });

Route::get('cart/content', CartContentController::class)->middleware('check.cart')->name('cart.content');
Route::put('cart/content', 'CartController@updateBulk')->name('cart.content.update');
Route::get('cart/count', 'CartController@count')->name('cart.count');
Route::resource('cart', CartController::class)->only('index', 'store', 'update', 'destroy');

Route::resource('checkout', CheckoutController::class);

Route::namespace('Admin')
    ->prefix('admin')
    ->as('admin.')
    ->middleware(['auth'])
    ->group(function ($router) {
        $router->get('/', HomeController::class);

        $router->resource('collections', CollectionController::class);
        $router->resource('categories', CategoryController::class);
        $router->resource('products', ProductController::class);
        $router->resource('colors', ColorController::class);
        $router->resource('sizes', SizeController::class);
        $router->resource('cloths', ClothController::class);
        $router->resource('products.colors', ProductColorController::class)->only('index', 'store');
        $router->resource('products.sizes', ProductSizeController::class)->only('index', 'store');
        $router->resource('products.cloths', ProductClothController::class)->only('index', 'store');
        $router->resource('products.pictures', ProductPictureController::class)->only('index', 'store', 'destroy');

        $router->resource('orders', OrderController::class);
        $router->resource('orders.details', OrderDetailController::class);

        $router->resource('first-page', FirstPagePictureController::class)->only('index', 'store', 'destroy');

        $router->resource('about', AboutController::class)->only('index', 'store');
        $router->resource('delivery', DeliveryController::class)->only('index', 'store');
        $router->resource('terms', TermsController::class)->only('index', 'store');
    });

app/Http/Controllers/SearchController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;

class SearchController extends Controller
{
    public function __invoke(Request $request)
    {
        $search = $request->search;
        $query = Product::with('pictures');

        if ($search) {
            $query->customSearch($search);
        }

        $products = $query->paginate(10);

        return view('search.index', compact('products', 'search'));
    }
}

resources/views/search/index.blade.php
@extends('layouts.master')

@section('content')
<div style="height:150px;"></div>
<div class="shop-wrapper hm-3-padding pt-120">
    <div class="container-fluid">
        <div class="grid-list-product-wrapper">
            <div class="product-grid product-view">
                <div class="row">
                    <h2>Rezultatele cautarii - {{ $search }}</h2>

                    @foreach ($products as $product)
                        <div class="product-width col-md-6 col-xl-3 col-lg-4 col-6">
                            <div class="product-wrapper mb-35">
                                <div class="product-img">
                                    <a href="{{ route('products.show', [$product->id]) }}">
                                        <img src="{{ asset('images/' . $product->getFirstPicture()->name) }}" alt="{{ $product->getFirstPicture()->alt }}">
                                    </a>
                                    @if ($product->discount)
                                        <div class="price-decrease">
                                            <span>{{ $product->getDiscount() }}% off</span>
                                        </div>
                                    @endif
                                    <div class="product-action-3">
                                        <a class="action-plus-2" title="Quick View" data-toggle="modal" onclick="getQuickProduct(event, {{ $product->id }})" data-target="#exampleModal" href="#">
                                            <i class="ti-plus"></i> Vizualizare rapida
                                        </a>
                                    </div>
                                </div>
                                <div class="product-content">
                                    <div class="product-title-wishlist">
                                        <div class="product-title-3">
                                            <h4><a href="{{ route('products.show', [$product->id]) }}">{{ $product->locale->pivot->name }}</a></h4>
                                        </div>
                                    </div>
                                    <div class="product-peice-addtocart">
                                        <div class="product-peice-3">
                                            @if ($product->discount)
                                                <span class="old">@float($product->locale->pivot->price) {{ $product->locale->symbol }}</span>
                                            @endif
                                            <span style="font-size:16px;"><b>@float($product->getFinalPrice())</b> {{ $product->locale->symbol }}</span>
                                        </div>
                                        <div class="product-addtocart centre">
                                            <a href="#" style="font-size:20px;"><i class="ti-shopping-cart"></i>Adauga in cos</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endforeach

            <div class="product-width col-md-6 col-xl-3 col-lg-4 col-6"
                {{ $products->links() }}
            </div>
        </div>
        </div>
        </div>
    </div>
</div>
@endsection