routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', HomeController::class)->name('home');
Route::get('about', AboutController::class)->name('about');
Route::get('delivery', DeliveryController::class)->name('delivery');
Route::get('terms', TermsController::class)->name('terms');
Route::get('search', SearchController::class)->name('search');

Route::resource('products', ProductController::class);
Route::resource('categories', CategoryController::class);
Route::resource('collections', CollectionController::class);

Route::get('quick-product/{product}', 'ProductController@quickShow');

Route::prefix('contact')
    ->group(function ($router) {
        $router->get('/', 'ContactController@index')->name('contact.index');
        $router->post('/', 'ContactController@store')->name('contact.store');
    });

Route::get('cart/content', CartContentController::class)->middleware('check.cart')->name('cart.content');
Route::put('cart/content', 'CartController@updateBulk')->name('cart.content.update');
Route::get('cart/count', 'CartController@count')->name('cart.count');
Route::resource('cart', CartController::class)->only('index', 'store', 'update', 'destroy');

Route::resource('checkout', CheckoutController::class);

Route::namespace('Admin')
    ->prefix('admin')
    ->as('admin.')
    ->middleware(['auth'])
    ->group(function ($router) {
        $router->get('/', HomeController::class);

        $router->resource('collections', CollectionController::class);
        $router->resource('categories', CategoryController::class);
        $router->resource('products', ProductController::class);
        $router->resource('colors', ColorController::class);
        $router->resource('sizes', SizeController::class);
        $router->resource('cloths', ClothController::class);
        $router->resource('products.colors', ProductColorController::class)->only('index', 'store');
        $router->resource('products.sizes', ProductSizeController::class)->only('index', 'store');
        $router->resource('products.cloths', ProductClothController::class)->only('index', 'store');
        $router->resource('products.pictures', ProductPictureController::class)->only('index', 'store', 'destroy');

        $router->resource('orders', OrderController::class);
        $router->resource('orders.details', OrderDetailController::class);

        $router->resource('first-page', FirstPagePictureController::class)->only('index', 'store', 'destroy');

        $router->resource('about', AboutController::class)->only('index', 'store');
        $router->resource('delivery', DeliveryController::class)->only('index', 'store');
        $router->resource('terms', TermsController::class)->only('index', 'store');
    });

app/Color.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Nicolaslopezj\Searchable\SearchableTrait;

class Color extends Model
{
    use SearchableTrait;

    protected $fillable = [
        'name', 'locale_id'
    ];

    protected $searchable = [
        'columns' => [
            'name' => 10
        ]
    ];

    public function locale()
    {
        return $this->belongsTo(Locale::class);
    }

    public function products()
    {
        return $this->belongsToMany(Product::class);
    }

    public function scopeByCategory($query, $categoryId)
    {
        $query->whereHas('products', function ($query) use ($categoryId) {
            $query->whereHas('category', function ($query) use ($categoryId) {
                $query->where('id', $categoryId);
            });
        });
    }

    public function scopeByCollection($query, $categoryId)
    {
        $query->whereHas('products', function ($query) use ($categoryId) {
            $query->whereHas('collection', function ($query) use ($categoryId) {
                $query->where('id', $categoryId);
            });
        });
    }
}

app/Http/Controllers/Admin/ColorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Color;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ColorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $colors = Color::paginate(10);

        return view('admin.colors.index', compact('colors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.colors.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $this->validate($request, [
            'name' => 'required|max:255|unique:colors,name'
        ]);

        Color::create($validated);

        return redirect()->route('admin.colors.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Color  $color
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return redirect()->route('admin.colors.edit', $id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Color  $color
     * @return \Illuminate\Http\Response
     */
    public function edit(Color $color)
    {
        return view('admin.colors.edit', compact('color'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Color  $color
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Color $color)
    {
        $validated = $this->validate($request, [
            'name' => 'required|min:1|max:255'
        ]);

        $color->update($validated);

        return redirect()->route('admin.colors.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Color  $color
     * @return \Illuminate\Http\Response
     */
    public function destroy(Color $color)
    {
        //
    }
}

resources/views/admin/colors/create.blade.php
@extends('adminlte::page')

@section('content')
    @box
        @slot('buttons')
            <a href="{{ route('admin.colors.index') }}" class="btn btn-default">
                <i class="fa fa-backward"></i>
                Inapoi
            </a>
        @endslot

        {!! Form::open()->route('admin.colors.store') !!}
            {!! Form::text('name', 'Nume') !!}
            {!! Form::submit('Salveaza')->success() !!}
        {!! Form::close() !!}
    @endbox
@endsection

resources/views/admin/colors/edit.blade.php
@extends('adminlte::page')

@section('content')
    @box
        @slot('buttons')
            Editeaza culoare #{{ $color->id }}
        @endslot

        {!! Form::open()->put()->route('admin.colors.update', [$color->id])->fill($color) !!}
            {!! Form::text('name', 'Nume') !!}
            {!! Form::submit('Modifica') !!}
            {!! Form::anchor('Inapoi')->route('admin.products.index') !!}

        {!! Form::close() !!}
    @endbox
@endsection

resources/views/admin/colors/index.blade.php
@extends('adminlte::page')

@section('content')
    @box
        @slot('buttons')
            <div class="col-md-6">
                @add(['route' => 'admin.colors.create', 'name' => 'culoare'])
                @endadd
            </div>

            <div class="col-md-6">
                @search(['route' => 'admin.sizes.index'])
                @endsearch
            </div>
        @endslot

        @if ($colors->count())
            <table class="table table-bordered table-hover">
                @theader(['columns' => [
                    'id' => 'Id',
                    'name' => 'Nume',
                    'created_at' => 'Creat la',
                    'updated_at' => 'Modificat la',
                    'none' => 'Actiuni'
                ]])
                @endtheader

                <tbody>
                    @foreach ($colors as $color)
                        <tr>
                            <td>{{ $color->id }}</td>
                            <td>{{ $color->name }}</td>
                            <td>{{ $color->created_at->format('d.m.Y H:i:s') }}</td>
                            <td>{{ $color->updated_at->format('d.m.Y H:i:s') }}</td>
                            <td>
                                <a href="{{ route('admin.colors.edit', $color->id) }}" class="btn btn-xs">
                                    <i class="fa fa-edit"></i>
                                </a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

            {{ $colors->links() }}
        @else
            Nu exista inregistrari
        @endif
    @endbox
@endsection

@section('js')
@endsection