routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', HomeController::class)->name('home');
Route::get('about', AboutController::class)->name('about');
Route::get('delivery', DeliveryController::class)->name('delivery');
Route::get('terms', TermsController::class)->name('terms');
Route::get('search', SearchController::class)->name('search');

Route::resource('products', ProductController::class);
Route::resource('categories', CategoryController::class);
Route::resource('collections', CollectionController::class);

Route::get('quick-product/{product}', 'ProductController@quickShow');

Route::prefix('contact')
    ->group(function ($router) {
        $router->get('/', 'ContactController@index')->name('contact.index');
        $router->post('/', 'ContactController@store')->name('contact.store');
    });

Route::get('cart/content', CartContentController::class)->middleware('check.cart')->name('cart.content');
Route::put('cart/content', 'CartController@updateBulk')->name('cart.content.update');
Route::get('cart/count', 'CartController@count')->name('cart.count');
Route::resource('cart', CartController::class)->only('index', 'store', 'update', 'destroy');

Route::resource('checkout', CheckoutController::class);

Route::namespace('Admin')
    ->prefix('admin')
    ->as('admin.')
    ->middleware(['auth'])
    ->group(function ($router) {
        $router->get('/', HomeController::class);

        $router->resource('collections', CollectionController::class);
        $router->resource('categories', CategoryController::class);
        $router->resource('products', ProductController::class);
        $router->resource('colors', ColorController::class);
        $router->resource('sizes', SizeController::class);
        $router->resource('cloths', ClothController::class);
        $router->resource('products.colors', ProductColorController::class)->only('index', 'store');
        $router->resource('products.sizes', ProductSizeController::class)->only('index', 'store');
        $router->resource('products.cloths', ProductClothController::class)->only('index', 'store');
        $router->resource('products.pictures', ProductPictureController::class)->only('index', 'store', 'destroy');

        $router->resource('orders', OrderController::class);
        $router->resource('orders.details', OrderDetailController::class);

        $router->resource('first-page', FirstPagePictureController::class)->only('index', 'store', 'destroy');

        $router->resource('about', AboutController::class)->only('index', 'store');
        $router->resource('delivery', DeliveryController::class)->only('index', 'store');
        $router->resource('terms', TermsController::class)->only('index', 'store');
    });

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Nicolaslopezj\Searchable\SearchableTrait;

class Category extends Model
{
    use SearchableTrait;

    protected $fillable = [
        'name', 'is_active'
    ];

    protected $casts = [
        'is_active' => 'boolean'
    ];

    protected $searchable = [
        'columns' => [
            'name' => 10
        ]
    ];

    public function scopeActive($query)
    {
        $query->where('is_active', true);
    }

    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $categories = Category::search($request->search)
            ->orderBy($request->input('sort', 'id'), $request->input('order', 'asc'))
            ->paginate(10);

        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $this->validate($request, [
            'name' => 'required|max:255|unique:categories,name'
        ]);

        Category::create($validated);

        return redirect()->route('admin.categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return redirect()->route('admin.categories.edit', $id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('admin.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $validated = $this->validate($request, [
            'name' => 'required|min:1|max:255'
        ]);

        $category->update($validated);

        return redirect()->route('admin.categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;
use App\Product;
use App\Color;
use App\Size;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return redirect()->route('categories.show', [1]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show($categoryId)
    {
        $products = Product::with('pictures', 'sizes', 'colors')
            ->byCategory($categoryId)
            ->paginate(10);

        $colors = Color::byCategory($categoryId)->get();
        $sizes = Size::byCategory($categoryId)->get();

        return view('products.index', compact('products', 'colors', 'sizes'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //
    }
}

resources/views/admin/categories/create.blade.php
@extends('adminlte::page')

@section('content')
    @box
        @slot('buttons')
            <a href="{{ route('admin.categories.index') }}" class="btn btn-default">
                <i class="fa fa-backward"></i>
                Inapoi
            </a>
        @endslot

        {!! Form::open()->route('admin.categories.store') !!}
            {!! Form::text('name', 'Nume') !!}
            {!! Form::select('is_active', [0 => 'Nu', 1 => 'Da'], 'E activ') !!}
            {!! Form::submit('Salveaza')->success() !!}
        {!! Form::close() !!}
    @endbox
@endsection

resources/views/admin/categories/edit.blade.php
@extends('adminlte::page')

@section('content')
    @box
        @slot('buttons')
            Editeaza culoare #{{ $category->id }}
        @endslot

        {!! Form::open()->put()->route('admin.categories.update', [$category->id])->fill($category) !!}
            {!! Form::text('name', 'Nume') !!}
            {!! Form::select('is_active', [0 => 'Nu', 1 => 'Da'], 'E activ') !!}
            {!! Form::submit('Modifica') !!}
            {!! Form::anchor('Inapoi')->route('admin.categories.index') !!}

        {!! Form::close() !!}
    @endbox
@endsection

resources/views/admin/categories/index.blade.php
@extends('adminlte::page')

@section('content')
    @box
        @slot('buttons')
            <div class="col-md-6">
                @add(['route' => 'admin.categories.create', 'name' => 'categorie'])
                @endadd
            </div>

            <div class="col-md-6">
                @search(['route' => 'admin.categories.index'])
                @endsearch
            </div>
        @endslot

        @if ($categories->count())
            <table class="table table-bordered table-hover">
                @theader(['columns' => [
                    'id' => 'Id',
                    'name' => 'Nume',
                    'is_active' => 'E activ',
                    'created_at' => 'Creat la',
                    'updated_at' => 'Modificat la',
                    'none' => 'Actiuni'
                ]])
                @endtheader

                <tbody>
                    @foreach ($categories as $category)
                        <tr>
                            <td>{{ $category->id }}</td>
                            <td>{{ $category->name }}</td>
                            <td>{{ $category->is_active ? 'Da' : 'Nu' }}</td>
                            <td>{{ $category->created_at->format('d.m.Y H:i:s') }}</td>
                            <td>{{ $category->updated_at->format('d.m.Y H:i:s') }}</td>
                            <td>
                                <a href="{{ route('admin.categories.edit', $category->id) }}" class="btn btn-xs">
                                    <i class="fa fa-edit"></i>
                                </a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

            {{ $categories->links() }}
        @else
            Nu exista inregistrari
        @endif
    @endbox
@endsection

@section('js')
@endsection